name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: .ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          install_local_path_provisioner: true
        if: steps.lint.outputs.changed == 'true'

      - name: sleep
        run: "echo home: $HOME; pwd; ls -la $HOME"

      - name: Install Ingress Controller
        uses: "deliverybot/helm@v1"
        env:
          KUBECONFIG: .kube/config
        with:
          track: "stable"
          chart: "nginx-ingress"
          release: nginx-ingress
          namespace: kube-system
          helm: helm3
          values: |
            controller:
              service:
                type: NodePort

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
          config: .ct.yaml
